export const SET_GEOLOCATION = "SET_GEOLOCATION";
export const SET_GEO_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_PRAYER_ERROR_MESSAGE = "SET_GEO_ERROR_MESSAGE";
export const SET_ISLOADING = "SET_ISLOADING";
export const SET_INPUT_FIELD = "SET_INPUT_FIELD";
export const SET_METHOD = "SET_METHOD";
export const SET_PERIOD = "SET_PERIOD";
export const SET_LANGUAGE = "SET_LANGUAGE";